workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      node: latest
      npm: latest
      java: 17
      groups:
        - default

    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          npx expo prebuild
          npx expo run:android --variant release

    artifacts:
      - android/app/build/outputs/**/*.apk
